apiVersion: v1
kind: ConfigMap
metadata: 
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
  - userarn: arn:aws:iam::123456789
    username: designated_user
    groups:
      - system:masters